/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuoteRequest = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const CustomerReview = IDL.Record({
  'customerName' : IDL.Text,
  'serviceType' : IDL.Text,
  'feedback' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat8,
});

export const idlService = IDL.Service({
  'getAllRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(CustomerReview)], ['query']),
  'getCustomerReview' : IDL.Func([IDL.Text], [CustomerReview], ['query']),
  'getQuoteRequest' : IDL.Func([IDL.Text], [QuoteRequest], ['query']),
  'getReviewsByService' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CustomerReview)],
      ['query'],
    ),
  'searchQuoteRequestsByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(QuoteRequest)],
      ['query'],
    ),
  'submitCustomerReview' : IDL.Func(
      [IDL.Text, IDL.Nat8, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitQuoteRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuoteRequest = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const CustomerReview = IDL.Record({
    'customerName' : IDL.Text,
    'serviceType' : IDL.Text,
    'feedback' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat8,
  });
  
  return IDL.Service({
    'getAllRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(CustomerReview)], ['query']),
    'getCustomerReview' : IDL.Func([IDL.Text], [CustomerReview], ['query']),
    'getQuoteRequest' : IDL.Func([IDL.Text], [QuoteRequest], ['query']),
    'getReviewsByService' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CustomerReview)],
        ['query'],
      ),
    'searchQuoteRequestsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(QuoteRequest)],
        ['query'],
      ),
    'submitCustomerReview' : IDL.Func(
        [IDL.Text, IDL.Nat8, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitQuoteRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };